package ab.model.chat;

public enum MessageType {
    TEXT, USER_ADDED, USER_REMOVED,
    NAME_REQUEST, USER_NAME, NAME_ACCEPTED,
    SERVER_FOUND, PASSWORD_REQUEST, PASSWORD_REPLY, PASSWORD_ACCEPTED, CONNECTION_REJECTED
}
